[project]
name = "paulst.github.io"
version = "1.0.0"
requires-python = ">=3.13"
dependencies = [
    "pelican[markdown]>=4.11.0",
    "minchin-pelican-plugins-summary>=1.3.0",
    "typogrify>=2.1.0",
    "beautifulsoup4>=4.14.3",
    "pelican-neighbors>=1.2.0",
    "pelican-render-math>=1.0.5",
]
